/**
 * Minimal print-friendly HTML for Puppeteer → PDF (interview Q&A guide).
 */
function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildInterviewGuideHtml({ jobDescriptionPreview, interviewQa }) {
  const jd = escapeHtml(jobDescriptionPreview || "—");
  const items = Array.isArray(interviewQa) ? interviewQa : [];

  const blocks = items
    .map((row, i) => {
      const q = escapeHtml(row.question || "");
      const brA = escapeHtml(row.answer || "").replace(/\r\n|\r|\n/g, "<br />");
      return `
    <div class="qa">
      <div class="qi">${i + 1}.</div>
      <div class="qb">
        <p class="q">${q}</p>
        <p class="a">${brA}</p>
      </div>
    </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Interview guide — 25 Q&amp;A</title>
  <style>
    @page { margin: 14mm; }
    * { box-sizing: border-box; }
    body {
      font-family: "Segoe UI", system-ui, -apple-system, Roboto, "Helvetica Neue", Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.45;
      color: #1a1a1a;
      margin: 0;
      padding: 8px 0 24px;
    }
    h1 {
      font-size: 18pt;
      margin: 0 0 10px;
      color: #0f172a;
    }
    .sub {
      font-size: 9.5pt;
      color: #475569;
      margin: 0 0 20px;
      padding: 10px 12px;
      background: #f1f5f9;
      border-left: 4px solid #3b82f6;
      border-radius: 4px;
    }
    .qa {
      display: flex;
      gap: 10px;
      margin: 0 0 14px;
      page-break-inside: avoid;
    }
    .qi {
      flex: 0 0 22px;
      font-weight: 700;
      color: #2563eb;
    }
    .qb { flex: 1; min-width: 0; }
    .q {
      font-weight: 700;
      margin: 0 0 6px;
      color: #0f172a;
    }
    .a {
      margin: 0;
      color: #334155;
    }
    .foot {
      margin-top: 28px;
      font-size: 8.5pt;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <h1>Top 25 interview questions &amp; answers</h1>
  <p class="sub"><strong>Job context (excerpt):</strong> ${jd}</p>
  ${blocks}
  <p class="foot">Generated by SN Algora AI — practice answers; adapt with your real experience.</p>
</body>
</html>`;
}

module.exports = { buildInterviewGuideHtml };
